services:
  hypha-workflow-db:
    image: postgres:14.3-alpine
    container_name: hypha-workflow-db
    ports:
      - "6434:5432"
    environment:
      POSTGRES_USER: ${HYPHA_WORKFLOW_DB_USERNAME}
      POSTGRES_PASSWORD: ${HYPHA_WORKFLOW_DB_PASSWORD}
      POSTGRES_DB: myc_hypha_workflow
    volumes:
      - ./pg_workflow/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || pg_isready"
      interval: 5s
      timeout: 2s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  hypha-workflow:
    image: "mycesys/hypha-workflow:${HYPHA_WORKFLOW_VERSION}"
    container_name: hypha-workflow
    restart: on-failure
    ports:
      - "8082:8082"
    healthcheck:
      test: curl -s http://localhost:8082/actuator/health| grep UP || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: ${HYPHA_WORKFLOW_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_WORKFLOW_LIMIT_MAX_RAM}
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://hypha-workflow-db:5432/myc_hypha_workflow
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hypha-workflow-db:5432/myc_hypha_workflow
    env_file:
      - ./.env
    depends_on:
      hypha-workflow-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
