services:
  hypha-resources-db:
    image: postgres:14.3-alpine
    container_name: hypha-resources-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${HYPHA_RESOURCE_MANAGER_DB_USERNAME}
      POSTGRES_PASSWORD: ${HYPHA_RESOURCE_MANAGER_DB_PASSWORD}
      POSTGRES_DB: myc_hypha_rm
    volumes:
      - ./pg_rm/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || pg_isready"
      interval: 5s
      timeout: 2s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  hypha-resources:
    image: "mycesys/hypha-resources:${HYPHA_RESOURCES_VERSION}"
    container_name: hypha-resources
    restart: on-failure
    ports:
      - "8096:8096"
    healthcheck:
      test: curl -s http://localhost:8096/actuator/health| grep UP || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: ${HYPHA_RESOURCE_MANAGER_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_RESOURCE_MANAGER_LIMIT_MAX_RAM}
    volumes:
      - ./ssh/keys:/ssh/keys
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://hypha-resources-db:5432/myc_hypha_rm
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hypha-resources-db:5432/myc_hypha_rm
      - SSH_DEFAULT_KEY_PATH=/ssh/keys/hypha
    env_file:
      - ./.env
    depends_on:
      hypha-resources-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
