services:
  hypha-files-db:
    image: postgres:14.3-alpine
    container_name: hypha-files-db
    ports:
      - "6632:5432"
    environment:
      POSTGRES_USER: ${HYPHA_FILES_MANAGER_DB_USERNAME}
      POSTGRES_PASSWORD: ${HYPHA_FILES_MANAGER_DB_PASSWORD}
      POSTGRES_DB: fmdb
    volumes:
      - ./pg_fm/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || pg_isready"
      interval: 5s
      timeout: 2s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  hypha-files:
    image: "mycesys/hypha-files:${HYPHA_FILES_VERSION}"
    container_name: hypha-files
    restart: on-failure
    ports:
      - "8097:8097"
    healthcheck:
      test: curl -s http://localhost:8097/actuator/health| grep UP || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: ${HYPHA_FILES_MANAGER_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_FILES_MANAGER_LIMIT_MAX_RAM}
    volumes:
      - ./files/data:/server/data
      - ./ssh/keys:/ssh/keys
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://hypha-files-db:5432/fmdb
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hypha-files-db:5432/fmdb
      - SSH_DEFAULT_KEY_PATH=/ssh/keys/hypha
      - STORAGE_LOCAL_PATH=/server/data
    env_file:
      - ./.env
    depends_on:
      hypha-files-db:
        condition: service_healthy
      consul:
        condition: service_started
      vault:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
