# version: '3.8'
# services:

include:
  # Consul
  - path: ../consul/docker-compose.yml
    project_directory: ../consul

  # Vault
  - path: ../vault/docker-compose.yml
    project_directory: ../vault
    env_file: ../allinone/.env

  # RabbitMQ
  - path: ../rabbitmq/docker-compose.yml
    project_directory: ../allinone

  # Hub Auth
  - path: ../hub-auth/docker-compose.yml
    project_directory: ../allinone

  # Hypha Files
  - path: ../hypha-files/docker-compose.yml
    project_directory: ../allinone

  # Hypha Resources
  - path: ../hypha-resources/docker-compose.yml
    project_directory: ../allinone

  # Hypha Tasks
  - path: ../hypha-tasks/docker-compose.yml
    project_directory: ../allinone

  # Hypha Core
  - path: ../hypha-core/docker-compose.yml
    project_directory: ../allinone

  # Hypha Dashboard
  - path: ../hypha-dashboard/docker-compose.yml
    project_directory: ../allinone

  # Hypha Workflow
  - path: ../hypha-workflow/docker-compose.yml
    project_directory: ../allinone

  # Hypha BFF
  - path: ../hypha-bff/docker-compose.yml
    project_directory: ../allinone

  # Hypha Gateway
  - path: ../hypha-gateway/docker-compose.yml
    project_directory: ../allinone

  # Hypha UI
  - path: ../hypha-ui/docker-compose.yml
    project_directory: ../allinone

  # Hub UI
  - path: ../hub-ui/docker-compose.yml
    project_directory: ../allinone

  # Hypha Internal
  - path: ../hypha-internal/docker-compose.yml
    project_directory: ../allinone
